/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ScanRecord = IDL.Record({
  'url' : IDL.Text,
  'verdict' : IDL.Text,
  'timestamp' : IDL.Int,
  'riskScore' : IDL.Nat,
});
export const BreakdownItem = IDL.Record({
  'status' : IDL.Text,
  'rule' : IDL.Text,
  'description' : IDL.Text,
  'detail' : IDL.Text,
});
export const ScanResult = IDL.Record({
  'breakdown' : IDL.Vec(BreakdownItem),
  'verdict' : IDL.Text,
  'riskScore' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getScanHistory' : IDL.Func([IDL.Nat], [IDL.Vec(ScanRecord)], ['query']),
  'getThreatFeed' : IDL.Func([], [IDL.Vec(ScanRecord)], ['query']),
  'scanUrl' : IDL.Func([IDL.Text], [ScanResult], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ScanRecord = IDL.Record({
    'url' : IDL.Text,
    'verdict' : IDL.Text,
    'timestamp' : IDL.Int,
    'riskScore' : IDL.Nat,
  });
  const BreakdownItem = IDL.Record({
    'status' : IDL.Text,
    'rule' : IDL.Text,
    'description' : IDL.Text,
    'detail' : IDL.Text,
  });
  const ScanResult = IDL.Record({
    'breakdown' : IDL.Vec(BreakdownItem),
    'verdict' : IDL.Text,
    'riskScore' : IDL.Nat,
  });
  
  return IDL.Service({
    'getScanHistory' : IDL.Func([IDL.Nat], [IDL.Vec(ScanRecord)], ['query']),
    'getThreatFeed' : IDL.Func([], [IDL.Vec(ScanRecord)], ['query']),
    'scanUrl' : IDL.Func([IDL.Text], [ScanResult], []),
  });
};

export const init = ({ IDL }) => { return []; };