/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BreakdownItem {
  'status' : string,
  'rule' : string,
  'description' : string,
  'detail' : string,
}
export interface ScanRecord {
  'url' : string,
  'verdict' : string,
  'timestamp' : bigint,
  'riskScore' : bigint,
}
export interface ScanResult {
  'breakdown' : Array<BreakdownItem>,
  'verdict' : string,
  'riskScore' : bigint,
}
export interface _SERVICE {
  /**
   * / Returns up to `limit` most-recent scans (newest first).
   * / Pass 0 to get all.
   */
  'getScanHistory' : ActorMethod<[bigint], Array<ScanRecord>>,
  /**
   * / Returns up to 20 most-recent phishing/suspicious scans (newest first).
   */
  'getThreatFeed' : ActorMethod<[], Array<ScanRecord>>,
  'scanUrl' : ActorMethod<[string], ScanResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];